name: dev
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda
  - anaconda-client
  - anaconda-project
  - conda
  - conda-content-trust
  - conda-pack
  - conda-package-handling
  - conda-token
  - flake8
  - flask
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jinja2
  - jinja2-time
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - numpy-base
  - numpydoc
  - pandas
  - pip
  - plotly
  - pylint
  - pytest
  - python=3.10.4
  - python-dateutil
  - python-fastjsonschema
  - requests
  - scipy
  - scikit-image
  - scikit-learn
  - scikit-learn-intelex
  - sqlalchemy
  - sqlite
  - statsmodels
  - xlrd
  - xlsxwriter
  - xlwings
