name: Test Jupyter Notebooks
on: [push]
jobs:
  build-docs:
    name: Building on (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    # See: https://github.com/marketplace/actions/setup-miniconda
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        auto-update-conda: true
        miniforge-variant: Mambaforge
        channels: conda-forge
        python-version: 3.10
        activate-environment: dev
        environment-file: env_files/environment.yml
        use-mamba: true

    - name: Build environment
    run:
      conda activate dev

    - name: Run script to test Jupyter notebooks
      run: |
        cd scripts/jupyter_notebook_testing
        python jn_testing.py
