name: Test Jupyter Notebooks
on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
jobs:
  test_jupyter_notebook:
    name: Runs Jupyter notebook with dev Conda environment.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
      - name: Create the environment
        run: |
          conda env update --file env_files/environment.yml --name dev
      - name: Run script to test Jupyter notebooks
        run: |
        cd scripts/jupyter_notebook_testing
        python jn_testing.py
