name: Test Jupyter Notebooks
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

    # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: dev
          environment-file: env_files/environment.yml
          use-mamba: true

      - name: Build environment
        run:
          conda activate dev

      - name: Run script to test Jupyter notebooks
        run: |
          cd Jupyter_Notebooks
          python ../scripts/jupyter_notebook_testing/jn_testing.py
